name: Early Access

on:
  push:
    branches: [ master ]

env:
  JAVA_VERSION: '17.0.2'
  JAVA_DISTRO: 'temurin'

jobs:
  precheck:
    runs-on: ubuntu-20.04
    if: startsWith(github.event.head_commit.message, '[maven-release-plugin]') != true
    outputs:
      JAVA_VERSION: ${{ env.JAVA_VERSION }}
      JAVA_DISTRO: ${{ env.JAVA_DISTRO }}
      VERSION: ${{ steps.vars.outputs.VERSION }}
      TAG: ${{ steps.vars.outputs.TAG }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.JAVA_DISTRO }}

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Set environment
        id: vars
        shell: bash
        run: |
          TAG=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          VERSION=$TAG
          VERSION=${VERSION%-*}
          echo ::set-output name=VERSION::$VERSION
          echo ::set-output name=TAG::$TAG

  linux-bundles:
    needs: [precheck]
    uses: gluonhq/scenebuilder/.github/workflows/bundles-linux.yml@master
    with:
      java-version: ${{ needs.precheck.outputs.JAVA_VERSION }}
      java-distro: ${{ needs.precheck.outputs.JAVA_DISTRO }}
      version: ${{ needs.precheck.outputs.VERSION }}
      tag: ${{ needs.precheck.outputs.TAG }}
      test: true

  windows-bundles:
    needs: [precheck]
    uses: gluonhq/scenebuilder/.github/workflows/bundles-windows.yml@master
    secrets:
      WINDOWS_CERTIFICATE: ${{ secrets.WINDOWS_CERTIFICATE }}
      WINDOWS_PASSWORD: ${{ secrets.WINDOWS_PASSWORD }}
      WINDOWS_CERTNAME: ${{ secrets.WINDOWS_CERTNAME }}
    with:
      java-version: ${{ needs.precheck.outputs.JAVA_VERSION }}
      java-distro: ${{ needs.precheck.outputs.JAVA_DISTRO }}
      version: ${{ needs.precheck.outputs.VERSION }}
      tag: ${{ needs.precheck.outputs.TAG }}
      test: true

  mac-bundles:
    needs: [precheck]
    uses: gluonhq/scenebuilder/.github/workflows/bundles-mac.yml@master
    secrets:
      CERTIFICATES_FILE_BASE64: ${{ secrets.CERTIFICATES_FILE_BASE64 }}
      CERTIFICATES_PASSWORD: ${{ secrets.CERTIFICATES_PASSWORD }}
      NOTARIZATION_USERNAME: ${{ secrets.NOTARIZATION_USERNAME }}
      NOTARIZATION_PASSWORD: ${{ secrets.NOTARIZATION_PASSWORD }}
      MACSIGN_USER: ${{ secrets.GLUON_MACSIGN_USER }}
      MACSIGN_PREFIX: ${{ secrets.GLUON_MACSIGN_PREFIX }}
    with:
      java-version: ${{ needs.precheck.outputs.JAVA_VERSION }}
      java-distro: ${{ needs.precheck.outputs.JAVA_DISTRO }}
      version: ${{ needs.precheck.outputs.VERSION }}
      tag: ${{ needs.precheck.outputs.TAG }}
      test: true

  kit-bundles:
    needs: [precheck]
    uses: gluonhq/scenebuilder/.github/workflows/bundles-kit.yml@master
    with:
      java-version: ${{ needs.precheck.outputs.JAVA_VERSION }}
      java-distro: ${{ needs.precheck.outputs.JAVA_DISTRO }}
      version: ${{ needs.precheck.outputs.VERSION }}
      tag: ${{ needs.precheck.outputs.TAG }}

  early-access:
    needs: [precheck, linux-bundles, windows-bundles, mac-bundles, kit-bundles]
    if: endsWith(${{ needs.precheck.outputs.TAG }}, '-SNAPSHOT')
    runs-on: ubuntu-20.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Download all build artifacts
        uses: actions/download-artifact@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: ${{ needs.precheck.outputs.JAVA_VERSION }}
          distribution: ${{ needs.precheck.outputs.JAVA_DISTRO }}

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Release with JReleaser
        env:
          VERSION: ${{ needs.precheck.outputs.VERSION }}
          JRELEASER_GITHUB_TOKEN: ${{ secrets.GITHUB_ACCESS_TOKEN }}
        run: |
          mvn -B -ntp -pl :parent -DartifactsDir=artifacts jreleaser:release

      - name: JReleaser output
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: jreleaser-logs
          path: |
            target/jreleaser/trace.log
            target/jreleaser/output.properties